      - name: Detect Kernel Version
        id: kver
        run: |
          cd $GITHUB_WORKSPACE
          KERNEL_VER=$(make kernelversion)
          echo "kernel_ver=$KERNEL_VER" >> $GITHUB_OUTPUT

      - name: Add KernelSU
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/tiann/KernelSU ksu
          cd ksu
          git submodule update --init --recursive
          if [ -d "next/patches/${{ steps.kver.outputs.kernel_ver }}" ]; then
            git am next/patches/${{ steps.kver.outputs.kernel_ver }}/*
          else
            echo "⚠️ No matching KernelSU patch found for kernel version ${{ steps.kver.outputs.kernel_ver }}"
          fi
